# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'Free Trial (981685b1-f8c8-4d73-b6d3-81d567c7fcbd)'
    Action: 'Start Azure App Service'
    WebAppName: 'learningAppCS353'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial (981685b1-f8c8-4d73-b6d3-81d567c7fcbd)'
    appType: 'webAppLinux'
    WebAppName: 'learningAppCS353'
    deployToSlotOrASE: true
    ResourceGroupName: 'cs353group6'
    SlotName: 'production'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'NODE|lts'
    StartupCommand: 'dotnet run'